"""core-issues3.txt Phase 10.4: scripts/generate_ood_extension_corpus.py,
run for real (small scale) against the actual data/learning-v2/cycle-b2
corpus -- proves the governed OOD_TRIGGERING_CONFIG_OVERRIDES recipes
actually classify as their intended category at real simulation scale
(not merely asserted), that the refit signature library matches cycle-b2's
own recorded artifact exactly, and that every generated example is
targets_v2-schema-valid.

Real defect this module's own dry run found and fixed, not by inspection:
hydroswarm.data.scenarios.WNTRScenarioGenerator.generate_with_network
unconditionally zeroes missing_probability whenever
config.stage == CurriculumStage.CLEAN, silently overriding whatever value
the caller's ScenarioGenerationConfig actually requested -- a
missing_probability-based OOD-triggering batch cycling through every
CurriculumStage (including CLEAN) would fail to trigger for ~1/5 of its
scenarios. test_severe_missingness_recipe_never_selects_clean_stage below
is the regression test for that fix (SEVERE_MISSINGNESS is the specific
category the bug was found on, though the fix -- never selecting CLEAN at
all -- applies to every category generated by this script).
"""

from __future__ import annotations

import json
import sys
import zlib
from pathlib import Path

import pytest

_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(_ROOT / "scripts"))

import generate_ood_extension_corpus as ood_ext  # noqa: E402

from hydroswarm.data.scenarios import CurriculumStage, ScenarioDatasetWriter  # noqa: E402
from hydroswarm.training.ood_categories import OODCategory  # noqa: E402
from hydroswarm.training.ood_labels import OOD_TRIGGERING_CONFIG_OVERRIDES  # noqa: E402
from hydroswarm.training.targets_v2 import validate_targets_v2  # noqa: E402

_CYCLE_B2_ROOT = Path("data/learning-v2/cycle-b2")

pytestmark = pytest.mark.skipif(
    not _CYCLE_B2_ROOT.exists(), reason="requires the real data/learning-v2/cycle-b2 corpus"
)


def test_severe_missingness_recipe_never_selects_clean_stage() -> None:
    stages = {ood_ext._stage_for_index(index) for index in range(20)}
    assert CurriculumStage.CLEAN not in stages


@pytest.mark.parametrize("category_name", sorted(category.value for category in OOD_TRIGGERING_CONFIG_OVERRIDES))
def test_recipe_reliably_triggers_its_category_at_real_scale(category_name: str, tmp_path: Path) -> None:
    overrides = {category.value: overrides for category, overrides in OOD_TRIGGERING_CONFIG_OVERRIDES.items()}[
        category_name
    ]
    topology_contexts = [
        ood_ext._TopologyContext(network_family, loader(), _CYCLE_B2_ROOT)
        for network_family, loader in ood_ext.TRAIN_TOPOLOGIES
    ]
    validated_topology_hashes = frozenset(context.topology_hash for context in topology_contexts)
    writer = ScenarioDatasetWriter(tmp_path / "scenarios")

    # Small real scale (3 per topology family = 9 total) -- exercises real
    # WNTR simulation and the real classify_ood_category call, not a
    # synthetic-shape fixture. Full-scale generation (400/category) is run
    # separately as a background job; this proves correctness, not volume.
    examples, report = ood_ext.generate_category(
        category_name,
        overrides,
        topology_contexts=topology_contexts,
        validated_topology_hashes=validated_topology_hashes,
        # zlib.crc32, not Python's hash() -- this project has already been
        # burned once by a test seeding itself from hash(str)'s per-process
        # randomization (see test_information_gain_is_nonnegative_within_
        # tolerance's fix); crc32 is deterministic across runs/processes.
        seed_base=zlib.crc32(category_name.encode()) % 1_000_000,
        count=9,
        writer=writer,
    )
    assert report["generated_count"] == 9  # would have raised already if any scenario mis-triggered
    expected_class_index = list(OODCategory).index(OODCategory(category_name))
    for example in examples:
        validate_targets_v2(example.targets, topology=example.topology)
        # Regression: generate_category previously verified each scenario's
        # OOD category but never actually attached ood_class_target to the
        # resulting example -- scenario_to_example alone does not compute
        # it. Caught running this test for real, not by inspection.
        assert "ood_class" in example.targets
        assert int(example.targets["ood_class"]) == expected_class_index


def test_seed_namespace_base_clears_cycle_b2s_own_occupied_range() -> None:
    """Regression for the real seed_family collision found while joining
    this corpus into cycle-b2-joint-v4 (build_stage_f_joint_corpus.py's
    `_cross_population_leakage` gate): the old default `--seed 91_000`
    landed a real ood-extension seed_family inside generate_cycle_b_corpus.
    py's own occupied range for the same network_family/topology_index
    (`("golden-reference", "golden-reference:910")` resolved to two
    different scenario_ids). Reuses generate_cycle_b_corpus's own real
    constants (not hand-copied numbers) so this stays correct if either
    script's counts ever change."""

    import generate_cycle_b_corpus as cycle_b2  # noqa: PLC0415

    max_topology_index = len(cycle_b2.TRAIN_TOPOLOGIES) - 1
    # cycle-b2's own worst-case absolute seed for training topology
    # `max_topology_index`: its SEVERE_MISSINGNESS OOD holdout (the
    # highest-offset population it generates for a training topology,
    # seed_base + 5_000_000) plus its largest index*100 stride.
    max_index_stride = max(count for _, count in cycle_b2._SPLITS) // len(cycle_b2.TRAIN_TOPOLOGIES)
    cycle_b2_max_seed = (
        71_000  # cycle_b2.main()'s own --seed default
        + max_topology_index * 10_000_000
        + 5_000_000
        + max_index_stride * 100
    )

    # The SMALLEST seed this script can ever emit (category_index=0,
    # topology_index=0, index=0) already exceeding cycle-b2's own LARGEST
    # occupied seed is sufficient to prove every range this script emits is
    # disjoint from every range cycle-b2 occupies.
    ood_extension_min_seed = ood_ext.SEED_NAMESPACE_BASE
    assert ood_extension_min_seed > cycle_b2_max_seed


def _write_index(path: Path, families: list[tuple[str, str]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as stream:
        for index, (network_id, seed_family) in enumerate(families):
            stream.write(
                json.dumps(
                    {
                        "scenario_id": f"scenario-{network_id}-{seed_family}-{index}",
                        "network_id": network_id,
                        "seed_family": seed_family,
                    }
                )
                + "\n"
            )


def test_verify_disjoint_seed_families_raises_on_real_collision(tmp_path: Path) -> None:
    cycle_b2_root = tmp_path / "cycle-b2"
    _write_index(cycle_b2_root / "tensors" / "train" / "index.jsonl", [("golden-reference", "910")])

    output = tmp_path / "cycle-b2-ood-extension"
    _write_index(output / "tensors" / "ood-EXTREME_DEMAND" / "index.jsonl", [("golden-reference", "910")])

    with pytest.raises(ValueError, match="seed_family collision"):
        ood_ext._verify_disjoint_seed_families(cycle_b2_root, output, ["EXTREME_DEMAND"])


def test_verify_disjoint_seed_families_passes_when_disjoint(tmp_path: Path) -> None:
    cycle_b2_root = tmp_path / "cycle-b2"
    _write_index(cycle_b2_root / "tensors" / "train" / "index.jsonl", [("golden-reference", "910")])

    output = tmp_path / "cycle-b2-ood-extension"
    _write_index(output / "tensors" / "ood-EXTREME_DEMAND" / "index.jsonl", [("golden-reference", "5000910")])

    result = ood_ext._verify_disjoint_seed_families(cycle_b2_root, output, ["EXTREME_DEMAND"])
    assert result["collisions"] == []
    assert result["cycle_b2_families_checked"] == 1
    assert result["new_families_checked"] == 1
