"""core-issues3.txt Phase 10.4: scripts/generate_ood_extension_corpus.py,
run for real (small scale) against the actual data/learning-v2/cycle-b2
corpus -- proves the governed OOD_TRIGGERING_CONFIG_OVERRIDES recipes
actually classify as their intended category at real simulation scale
(not merely asserted), that the refit signature library matches cycle-b2's
own recorded artifact exactly, and that every generated example is
targets_v2-schema-valid.

Real defect this module's own dry run found and fixed, not by inspection:
hydroswarm.data.scenarios.WNTRScenarioGenerator.generate_with_network
unconditionally zeroes missing_probability whenever
config.stage == CurriculumStage.CLEAN, silently overriding whatever value
the caller's ScenarioGenerationConfig actually requested -- a
missing_probability-based OOD-triggering batch cycling through every
CurriculumStage (including CLEAN) would fail to trigger for ~1/5 of its
scenarios. test_severe_missingness_recipe_never_selects_clean_stage below
is the regression test for that fix (SEVERE_MISSINGNESS is the specific
category the bug was found on, though the fix -- never selecting CLEAN at
all -- applies to every category generated by this script).
"""

from __future__ import annotations

import sys
import zlib
from pathlib import Path

import pytest

_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(_ROOT / "scripts"))

import generate_ood_extension_corpus as ood_ext  # noqa: E402

from hydroswarm.data.scenarios import CurriculumStage, ScenarioDatasetWriter  # noqa: E402
from hydroswarm.training.ood_categories import OODCategory  # noqa: E402
from hydroswarm.training.ood_labels import OOD_TRIGGERING_CONFIG_OVERRIDES  # noqa: E402
from hydroswarm.training.targets_v2 import validate_targets_v2  # noqa: E402

_CYCLE_B2_ROOT = Path("data/learning-v2/cycle-b2")

pytestmark = pytest.mark.skipif(
    not _CYCLE_B2_ROOT.exists(), reason="requires the real data/learning-v2/cycle-b2 corpus"
)


def test_severe_missingness_recipe_never_selects_clean_stage() -> None:
    stages = {ood_ext._stage_for_index(index) for index in range(20)}
    assert CurriculumStage.CLEAN not in stages


@pytest.mark.parametrize("category_name", sorted(category.value for category in OOD_TRIGGERING_CONFIG_OVERRIDES))
def test_recipe_reliably_triggers_its_category_at_real_scale(category_name: str, tmp_path: Path) -> None:
    overrides = {category.value: overrides for category, overrides in OOD_TRIGGERING_CONFIG_OVERRIDES.items()}[
        category_name
    ]
    topology_contexts = [
        ood_ext._TopologyContext(network_family, loader(), _CYCLE_B2_ROOT)
        for network_family, loader in ood_ext.TRAIN_TOPOLOGIES
    ]
    validated_topology_hashes = frozenset(context.topology_hash for context in topology_contexts)
    writer = ScenarioDatasetWriter(tmp_path / "scenarios")

    # Small real scale (3 per topology family = 9 total) -- exercises real
    # WNTR simulation and the real classify_ood_category call, not a
    # synthetic-shape fixture. Full-scale generation (400/category) is run
    # separately as a background job; this proves correctness, not volume.
    examples, report = ood_ext.generate_category(
        category_name,
        overrides,
        topology_contexts=topology_contexts,
        validated_topology_hashes=validated_topology_hashes,
        # zlib.crc32, not Python's hash() -- this project has already been
        # burned once by a test seeding itself from hash(str)'s per-process
        # randomization (see test_information_gain_is_nonnegative_within_
        # tolerance's fix); crc32 is deterministic across runs/processes.
        seed_base=zlib.crc32(category_name.encode()) % 1_000_000,
        count=9,
        writer=writer,
    )
    assert report["generated_count"] == 9  # would have raised already if any scenario mis-triggered
    expected_class_index = list(OODCategory).index(OODCategory(category_name))
    for example in examples:
        validate_targets_v2(example.targets, topology=example.topology)
        # Regression: generate_category previously verified each scenario's
        # OOD category but never actually attached ood_class_target to the
        # resulting example -- scenario_to_example alone does not compute
        # it. Caught running this test for real, not by inspection.
        assert "ood_class" in example.targets
        assert int(example.targets["ood_class"]) == expected_class_index
