"""Learned OOD category-label generation (core-issues2.txt Phase 4).

Assigns a governed OODCategory (ood_categories.py's already-existing
taxonomy and fail-closed behavior table) to a generated scenario, purely
from information already recorded on GeneratedScenario/ScenarioManifest --
no separate ScenarioGenerationConfig object needs threading through
generation, since scenarios.py's own manifest.model_mismatch dict already
records the roughness/tank/demand knobs used to generate this specific
scenario.

Thresholds are chosen relative to the corpus generator's own documented
in-distribution ranges (scripts/generate_cycle_b_corpus.py's
_degradation_probabilities and hydroswarm.data.scenarios.
ScenarioGenerationConfig's defaults, none of which are stage-varied for
demand/roughness/tank/drift), with a wide safety margin so no legitimate
in-distribution example -- including ADVERSARIAL-stage ones -- is
misclassified as OOD:

| Category               | In-distribution range (all stages)       | Threshold here     |
|-------------------------|-------------------------------------------|---------------------|
| SEVERE_MISSINGNESS      | missing_probability <= 0.08                | realized > 0.2      |
| EXTREME_DEMAND          | demand_regime in {0.8, 1.0, 1.2}           | outside [0.5, 1.5]  |
| TANK_STATE_SHIFT        | tank_level_variation_fraction == 0.1 (fixed)| > 0.25             |
| ROUGHNESS_MISMATCH      | roughness_variation_fraction == 0.05 (fixed)| > 0.15             |
| FROZEN_DRIFTING_SENSOR  | frozen_probability <= 0.06                 | > 0.5 of sensors ever frozen (frozen_mask only -- see classify_ood_category's inline comment for why drift_mask is deliberately excluded) |

Categories NOT generated by this module, documented rather than silently
skipped (Phase 4: "Only generate categories that can be reproduced and
validated correctly"):

- UNSEEN_SENSOR_LAYOUT: the current signature-artifact design fits over
  *every* junction as a candidate sensor
  (scout_labels.build_signature_artifact_for_network's own docstring: every
  junction is both a source and sample candidate), so there is no "trained
  sensor layout" concept the current generator can meaningfully violate yet.
- VALVE_PUMP_MISMATCH: scenarios.py's
  model_mismatch["valve_telemetry_incorrect"] is currently a curriculum-
  stage-keyed *label*, not an actual simulated valve/pump state
  perturbation (a pre-existing, separately documented generator gap --
  see hydroswarm.data.scenarios's own comments); labeling this category
  correctly needs real hydraulic perturbation logic that does not exist yet.
- TIMING_OUTSIDE_TRAINING_RANGE: start_time/duration outside the canonical
  bins (0,60,120,240)/(30,60,120) currently raises inside
  hydroswarm.training.corpus.scenario_to_example's ordinal-bin lookup (a
  ValueError, not a graceful OOD label) -- generating this category safely
  needs that lookup hardened first.
- UNSUPPORTED_NETWORK_ELEMENT_OR_INVALID_CALIBRATION: not a scenario-
  generation-time property at all; already governed by
  CalibrationArtifact.validate_runtime's existing fail-closed checks
  (Phase 1's audit) -- a corrupted-artifact test fixture, not a corpus
  target this module can assign.
"""

from __future__ import annotations

from typing import Collection

import numpy as np
import torch

from hydroswarm.data.scenarios import GeneratedScenario

from .ood_categories import OODCategory, topology_calibration_is_valid

#: See module docstring's threshold table.
SEVERE_MISSINGNESS_THRESHOLD = 0.2
EXTREME_DEMAND_BAND = (0.5, 1.5)
TANK_STATE_SHIFT_THRESHOLD = 0.25
ROUGHNESS_MISMATCH_THRESHOLD = 0.15
FROZEN_DRIFTING_SENSOR_THRESHOLD = 0.5

#: core-issues3.txt Phase 6.2: queryable (not just documented-in-prose)
#: record of which OODCategory members classify_ood_category can actually
#: return -- checkpoint/runtime metadata must never trust a category the
#: generator never produced (an untrained class), and the module docstring
#: above already enumerates exactly this split; these two constants make
#: that enumeration a fact code can assert against (see
#: test_ood_labels.py::test_classify_ood_category_only_ever_returns_a_
#: supported_category) rather than only a comment that could silently
#: drift from actual behavior.
SUPPORTED_OOD_CATEGORIES: frozenset[OODCategory] = frozenset({
    OODCategory.NONE,
    OODCategory.UNSEEN_TOPOLOGY,
    OODCategory.EXTREME_DEMAND,
    OODCategory.TANK_STATE_SHIFT,
    OODCategory.ROUGHNESS_MISMATCH,
    OODCategory.SEVERE_MISSINGNESS,
    OODCategory.FROZEN_DRIFTING_SENSOR,
})
UNSUPPORTED_OOD_CATEGORIES: frozenset[OODCategory] = frozenset(OODCategory) - SUPPORTED_OOD_CATEGORIES

#: core-issues3.txt Phase 6.3: a governed, versioned recipe of
#: ScenarioGenerationConfig overrides known to reliably trigger each
#: reproducible non-NONE category (verified against classify_ood_category
#: itself, not asserted from the threshold table alone -- see
#: test_ood_labels.py::test_every_recipe_override_reliably_triggers_its_
#: category). UNSEEN_TOPOLOGY is deliberately absent: it is not a
#: generation-config property at all (any config yields it once given an
#: unvalidated topology_hash at classification time), so it has no
#: generation-time override to record here.
#:
#: This is the reusable "which knobs to push" building block a real
#: balanced-OOD corpus-generation pass needs (Phase 6.3's "Generate a
#: separate, versioned, balanced OOD training extension"). Turning it into
#: an actual standalone corpus at Cycle-B2 scale -- real production
#: topologies, thousands of scenarios, plus the trained-model-dependent
#: metrics Phase 6.3 also requires (false-normal rate, macro F1,
#: calibration by category, unsafe non-abstention -- none of which can be
#: computed without a trained checkpoint, see control_labels.py's
#: identical structural dependency) -- is deferred: it needs dedicated
#: compute time this pass's CPU budget does not have free while the
#: cycle-b2-trajectories-v2 regeneration is still running, and most of its
#: required metrics are blocked on Phase 8's Stage-A checkpoint regardless.
OOD_TRIGGERING_CONFIG_OVERRIDES: dict[OODCategory, dict[str, object]] = {
    OODCategory.EXTREME_DEMAND: {"demand_regimes": (2.5,)},
    OODCategory.TANK_STATE_SHIFT: {"tank_level_variation_fraction": 0.6},
    OODCategory.ROUGHNESS_MISMATCH: {"roughness_variation_fraction": 0.4},
    OODCategory.SEVERE_MISSINGNESS: {"missing_probability": 0.6},
    OODCategory.FROZEN_DRIFTING_SENSOR: {"frozen_probability": 1.0, "sensor_count": 6},
}

#: Enum declaration order, matching targets_v2.TARGET_CLASS_COUNTS["ood_class"].
_OOD_CLASS_INDEX = {category: index for index, category in enumerate(OODCategory)}


def classify_ood_category(
    scenario: GeneratedScenario,
    *,
    topology_hash: str,
    validated_topology_hashes: Collection[str],
    broader_validated_artifact_exists: bool = False,
) -> OODCategory:
    """Deterministically derive this scenario's governed OODCategory from
    its own recorded generation metadata and realized observation arrays.

    Checked in priority order (most structural/severe first) -- a scenario
    could technically trip more than one threshold; the first (highest-
    priority) match is recorded as the single ood_class label.
    """

    if not topology_calibration_is_valid(
        topology_hash,
        validated_topology_hashes,
        broader_validated_artifact_exists=broader_validated_artifact_exists,
    ):
        return OODCategory.UNSEEN_TOPOLOGY

    mismatch = scenario.manifest.model_mismatch
    if mismatch.get("tank_level_fraction", 0.0) > TANK_STATE_SHIFT_THRESHOLD:
        return OODCategory.TANK_STATE_SHIFT
    if mismatch.get("roughness_fraction", 0.0) > ROUGHNESS_MISMATCH_THRESHOLD:
        return OODCategory.ROUGHNESS_MISMATCH

    demand_regime = scenario.manifest.incident.demand_regime
    if not (EXTREME_DEMAND_BAND[0] <= demand_regime <= EXTREME_DEMAND_BAND[1]):
        return OODCategory.EXTREME_DEMAND

    realized_missingness = float(1.0 - np.mean(scenario.observation_mask))
    if realized_missingness > SEVERE_MISSINGNESS_THRESHOLD:
        return OODCategory.SEVERE_MISSINGNESS

    # frozen_mask only, deliberately excluding drift_mask: drift_mask fires
    # once accumulated drift (hours * drift_per_hour) exceeds
    # quantization_step, which -- given long enough simulated duration --
    # eventually happens for every sensor even at drift_per_hour's tiny
    # in-distribution default (0.001, never stage-varied). It is a smooth
    # function of simulation length, not a discrete per-sensor fault
    # decision the way frozen_probability/communication_outage_probability
    # are, so it cannot cleanly separate "ordinary" from "OOD" the way
    # frozen_mask's genuine per-sensor Bernoulli draw can. A properly
    # reproducible drift-based OOD signal needs the original
    # drift_per_hour config value threaded through generation, not just
    # the realized array -- tracked as a known limitation, not silently
    # worked around.
    frozen_per_sensor = np.asarray(scenario.frozen_mask).any(axis=0)
    if frozen_per_sensor.size and float(np.mean(frozen_per_sensor)) > FROZEN_DRIFTING_SENSOR_THRESHOLD:
        return OODCategory.FROZEN_DRIFTING_SENSOR

    return OODCategory.NONE


def ood_class_target(category: OODCategory) -> dict[str, torch.Tensor]:
    """targets_v2's ood_class target: a single non-maskable categorical
    index (every example is classified, including in-distribution)."""

    return {"ood_class": torch.tensor(_OOD_CLASS_INDEX[category])}
