import type { IncidentView } from './types';

export const demoIncident: IncidentView = {
  id: 'HS-0041',
  networkId: 'Net3',
  status: 'APPROVAL',
  source: 'demo-fallback',
  offline: true,
  runtimeMs: 438,
  modelVersion: 'HydroSwarm-M 0.9.2',
  ood: 'NORMAL',
  approvalPending: true,
  candidateCoverage: 0.9,
  disagreement: 0.08,
  nodes: [
    {
      id: 'R1',
      kind: 'reservoir',
      coordinates: [-80.01, 35.01],
      probability: 0,
      concentration: 0,
      candidate: false,
    },
    {
      id: 'J104',
      kind: 'junction',
      coordinates: [-80.005, 35.008],
      probability: 0.02,
      concentration: 0,
      candidate: false,
    },
    {
      id: 'J109',
      kind: 'junction',
      coordinates: [-80, 35.012],
      probability: 0.05,
      concentration: 0.1,
      candidate: false,
      sensor: {
        id: 'S4',
        health: 'HEALTHY',
        quality: 0.98,
        ageMinutes: 2,
        pressure: 28.4,
        concentration: 0.1,
      },
    },
    {
      id: 'J117',
      kind: 'junction',
      coordinates: [-79.995, 35.015],
      probability: 0.76,
      concentration: 0.78,
      candidate: true,
    },
    {
      id: 'J121',
      kind: 'junction',
      coordinates: [-79.989, 35.011],
      probability: 0.11,
      concentration: 0.46,
      candidate: true,
    },
    {
      id: 'J123',
      kind: 'junction',
      coordinates: [-79.984, 35.006],
      probability: 0.03,
      concentration: 0.31,
      candidate: false,
      sensor: {
        id: 'S7',
        health: 'DRIFT',
        quality: 0.72,
        ageMinutes: 14,
        pressure: 26.9,
        concentration: 0.31,
      },
    },
    {
      id: 'J131',
      kind: 'junction',
      coordinates: [-79.978, 35.002],
      probability: 0.03,
      concentration: 0.18,
      candidate: false,
    },
    {
      id: 'T1',
      kind: 'tank',
      coordinates: [-79.992, 35.003],
      probability: 0,
      concentration: 0,
      candidate: false,
    },
  ],
  links: [
    { id: 'P1', source: 'R1', target: 'J104', flow: 32, concentration: 0 },
    { id: 'P2', source: 'J104', target: 'J109', flow: 27, concentration: 0.1 },
    { id: 'P3', source: 'J109', target: 'J117', flow: 22, concentration: 0.72 },
    { id: 'P4', source: 'J117', target: 'J121', flow: 19, concentration: 0.61, action: 'CLOSE' },
    { id: 'P5', source: 'J121', target: 'J123', flow: 13, concentration: 0.42 },
    { id: 'P6', source: 'J123', target: 'J131', flow: 9, concentration: 0.2, action: 'FLUSH' },
    { id: 'P7', source: 'T1', target: 'J123', flow: -6, concentration: 0.04 },
  ],
  candidates: [
    { nodeId: 'J117', probability: 0.76 },
    { nodeId: 'J121', probability: 0.11 },
    { nodeId: 'J109', probability: 0.05 },
  ],
  recommendedSample: {
    nodeId: 'J123',
    informationGain: 0.37,
    delayMinutes: 14,
    cost: 1.4,
    rationale: 'Best separation between the two remaining upstream hypotheses.',
  },
  evidence: {
    before: [
      { nodeId: 'J117', probability: 0.38 },
      { nodeId: 'J121', probability: 0.34 },
      { nodeId: 'J109', probability: 0.16 },
    ],
    after: [
      { nodeId: 'J117', probability: 0.76 },
      { nodeId: 'J121', probability: 0.11 },
      { nodeId: 'J109', probability: 0.05 },
    ],
    uncertaintyReduction: 0.41,
    nodesRemoved: 8,
  },
  plans: [
    {
      id: 'A',
      name: 'Aggressive isolation',
      exposureReduction: 0.61,
      pressureViolations: 4,
      serviceAvailability: 0.918,
      actions: 5,
      containmentMinutes: 31,
      status: 'REJECTED',
      rejectionReason: 'Pressure below 15 m for 23 minutes.',
    },
    {
      id: 'B',
      name: 'Isolate + controlled flush',
      exposureReduction: 0.48,
      pressureViolations: 0,
      serviceAvailability: 0.987,
      actions: 3,
      containmentMinutes: 44,
      status: 'RECOMMENDED',
    },
    {
      id: 'C',
      name: 'Monitor + flush only',
      exposureReduction: 0.33,
      pressureViolations: 0,
      serviceAvailability: 1,
      actions: 1,
      containmentMinutes: 68,
      status: 'VALID',
    },
  ],
  audit: [
    {
      sequence: 1,
      timestamp: '08:14:02',
      type: 'INCIDENT_DETECTED',
      actor: 'SENSOR S4',
      detail: 'Concentration crossed 0.001 mg/L.',
    },
    {
      sequence: 2,
      timestamp: '08:14:05',
      type: 'SOURCE_LOCALIZED',
      actor: 'SENTINEL',
      detail: 'Candidate region contains 11 nodes.',
    },
    {
      sequence: 3,
      timestamp: '08:14:08',
      type: 'SAMPLE_RECOMMENDED',
      actor: 'SCOUT',
      detail: 'J123; expected information gain 0.37.',
    },
    {
      sequence: 4,
      timestamp: '08:28:00',
      type: 'SAMPLE_RECEIVED',
      actor: 'OPERATOR',
      detail: 'Candidate region contracted to 3 nodes.',
    },
    {
      sequence: 5,
      timestamp: '08:28:03',
      type: 'PLAN_REJECTED',
      actor: 'WNTR VERIFIER',
      detail: 'Plan A caused 4 pressure violations.',
    },
    {
      sequence: 6,
      timestamp: '08:28:05',
      type: 'PLAN_VERIFIED',
      actor: 'WNTR VERIFIER',
      detail: 'Plan B preserved 98.7% service availability.',
    },
  ],
  benchmarks: [
    {
      metric: 'Top-1 source localization',
      value: '100%',
      comparison: '3 seeded golden runs',
      status: 'PASS',
    },
    {
      metric: 'True-source posterior',
      value: '99.41%',
      comparison: 'uniform prior to J2',
      status: 'PASS',
    },
    {
      metric: 'Candidate contraction',
      value: '4 to 1',
      comparison: '1.0 bit sample IG',
      status: 'PASS',
    },
    {
      metric: 'Unsafe / safe plan checks',
      value: '100% / 100%',
      comparison: 'exact WNTR verifier',
      status: 'PASS',
    },
    {
      metric: 'Modeled exposure reduction',
      value: '14,723 mg',
      comparison: 'versus exact no response',
      status: 'PASS',
    },
    {
      metric: 'Latency / Python allocation peak',
      value: '1.51 s / 1.17 MB',
      comparison: 'native WNTR RAM excluded',
      status: 'PASS',
    },
    {
      metric: 'HydroCore S / M / L checkpoint',
      value: 'Not run',
      comparison: 'governed checkpoint absent',
      status: 'NOT RUN',
    },
  ],
  explanation:
    'Plan B is preferred because exact simulation found no pressure violations while reducing estimated exposure by 48% and preserving 98.7% service availability. Plan A was rejected despite higher exposure reduction because four nodes fell below the pressure threshold.',
};
