"""Run every governed corpus gate before a Cycle A/B-style corpus may be used
for training (overnight-plan.txt Task 0.5, core-issues.txt Phase 3 item 15).

Stops (nonzero exit) and reports which gate(s) failed rather than partially
succeeding -- a corpus that fails any gate here must not be trained on. Every
gate operates on real, already-generated corpus artifacts (dataset-report.json
/ label-audit.json / tensors/ shards / scenarios/ manifests); none of them
regenerate or mutate the corpus.

Gates:

1. shard_checksums          every split + ood-<category> directory's shards
                             match their recorded sha256
                             (ShardedScenarioDataset.verify_shard_checksums()).
2. finite_values             label-audit.json recorded zero finite-value
                             violations, computed at generation time from the
                             RAW (pre-normalization) examples. Deliberately
                             does not re-check the normalized tensors:
                             NormalizationStats.transform() unconditionally
                             calls nan_to_num, so a finite check against
                             already-normalized data would trivially always
                             pass and catch nothing.
3. target_mask_validation    label-audit.json recorded zero impossible_labels
                             across every split.
4. leakage                   label-audit.json's cross_split_leakage: zero
                             scenario_id_leaks, zero seed_family_leaks, zero
                             topology_hash_conflicts, zero examples missing
                             topology metadata.
5. topology_provenance       a sample of examples per network_id has its
                             recorded topology_hash and node_ids recomputed
                             independently from the real, pristine topology
                             file and compared for an exact match.
6. normalization_ownership   the saved normalization artifact is refit
                             directly from tensors/train (raw) and compared
                             byte-for-byte (fingerprint match) -- proof the
                             artifact was fit from this exact train split and
                             nothing else, not merely a claim in a log line.
7. label_audit_present       label-audit.json exists, is well-formed, and
                             sanity-baseline accuracies were computed only for
                             train/validation/calibration, never test/ood.
8. mask_round_trip            collate_variable_topology, given two real
                             examples drawn from two different real
                             topologies in this corpus, preserves each
                             example's own stored sensor_mask/quality_mask/
                             node_mask exactly in the region it owns and
                             zeroes them in the padded region -- plus the
                             existing tests/unit/test_variable_collate.py
                             regression suite.
9. deterministic_replay       a sample of train/validation/calibration
                             scenarios are regenerated byte-for-byte from
                             their recorded seed/config and compared against
                             the stored .npz arrays and replay_sha256.
                             development_holdout is excluded: the plain
                             curriculum path and the two OOD-holdout helpers
                             write into the same manifest file using
                             different degradation-probability formulas that
                             cannot be told apart from the manifest alone, so
                             replaying it would risk a false failure from a
                             guessed formula, not a real one.
"""

from __future__ import annotations

import argparse
import json
import random
import subprocess
import sys
from pathlib import Path
from typing import Any
from uuid import UUID

import numpy as np

from generate_cycle_b_corpus import DEV_OOD_TOPOLOGY, TRAIN_TOPOLOGIES, _degradation_probabilities

from hydroswarm.data.scenarios import (
    CurriculumStage,
    DatasetSplit,
    EventType,
    IncidentTruth,
    ScenarioManifest,
    WNTRScenarioGenerator,
)
from hydroswarm.data.scenarios import ScenarioGenerationConfig, network_sha256
from hydroswarm.preprocessing.schema import DEFAULT_FEATURE_SCHEMA, NormalizationStats
from hydroswarm.training import ShardedScenarioDataset, collate_variable_topology
from hydroswarm.training.data import ScenarioExample

REPO_ROOT = Path(__file__).resolve().parents[1]

_REPLAY_ELIGIBLE_SPLITS = (DatasetSplit.TRAIN, DatasetSplit.VALIDATION, DatasetSplit.CALIBRATION)


class GateFailure(Exception):
    pass


def _topology_loaders() -> dict[str, Any]:
    loaders = {name: loader for name, loader in TRAIN_TOPOLOGIES}
    dev_name, dev_loader = DEV_OOD_TOPOLOGY
    loaders[dev_name] = dev_loader
    return loaders


def _discover_split_dirs(tensors_root: Path) -> dict[str, str]:
    mapping: dict[str, str] = {}
    for candidate in sorted(tensors_root.iterdir()):
        if not candidate.is_dir() or not (candidate / "manifest.json").exists():
            continue
        mapping[candidate.name] = "development_holdout" if candidate.name.startswith("ood-") else candidate.name
    return mapping


def gate_shard_checksums(corpus_dir: Path, report: dict[str, Any]) -> None:
    tensors_root = corpus_dir / "tensors"
    split_dirs = _discover_split_dirs(tensors_root)
    checked = []
    for name, expected_split in split_dirs.items():
        dataset = ShardedScenarioDataset(tensors_root / name, expected_split=expected_split)
        dataset.verify_shard_checksums()
        checked.append({"split_dir": name, "example_count": len(dataset)})
    if not checked:
        raise GateFailure(f"no split directories found under {tensors_root}")
    report["checked_splits"] = checked


def _load_label_audit(corpus_dir: Path) -> dict[str, Any]:
    path = corpus_dir / "label-audit.json"
    if not path.exists():
        raise GateFailure(f"missing {path}")
    return json.loads(path.read_text(encoding="utf-8"))


def gate_finite_values(corpus_dir: Path, report: dict[str, Any]) -> None:
    audit = _load_label_audit(corpus_dir)
    violations = {
        split: data["finite_value_violations"]
        for split, data in audit["splits"].items()
        if data.get("finite_value_violations")
    }
    if violations:
        raise GateFailure(f"non-finite values recorded in raw generation audit: {violations}")
    report["splits_checked"] = sorted(audit["splits"])


def gate_target_mask_validation(corpus_dir: Path, report: dict[str, Any]) -> None:
    audit = _load_label_audit(corpus_dir)
    violations = {
        split: data["impossible_labels"]
        for split, data in audit["splits"].items()
        if data.get("impossible_labels")
    }
    if violations:
        raise GateFailure(f"impossible labels recorded in audit: {violations}")
    report["splits_checked"] = sorted(audit["splits"])


def gate_leakage(corpus_dir: Path, report: dict[str, Any]) -> None:
    audit = _load_label_audit(corpus_dir)
    leakage = audit["cross_split_leakage"]
    problems = {
        key: leakage[key]
        for key in ("scenario_id_leaks", "seed_family_leaks", "topology_hash_conflicts")
        if leakage.get(key)
    }
    if leakage.get("examples_missing_topology_metadata"):
        problems["examples_missing_topology_metadata"] = leakage["examples_missing_topology_metadata"]
    if problems:
        raise GateFailure(f"cross-split leakage detected: {problems}")
    report["cross_split_leakage"] = leakage


def gate_topology_provenance(corpus_dir: Path, report: dict[str, Any], *, sample_per_topology: int) -> None:
    tensors_root = corpus_dir / "tensors"
    loaders = _topology_loaders()
    pristine_by_family = {}
    checked: dict[str, Any] = {}
    rng = random.Random(20260805)

    split_dirs = _discover_split_dirs(tensors_root)
    examples_by_family: dict[str, list[ScenarioExample]] = {}
    for name, expected_split in split_dirs.items():
        dataset = ShardedScenarioDataset(tensors_root / name, expected_split=expected_split)
        indices = list(range(len(dataset)))
        rng.shuffle(indices)
        for position in indices[: max(sample_per_topology, 4)]:
            example = dataset[position]
            examples_by_family.setdefault(example.network_id, []).append(example)

    for family, examples in examples_by_family.items():
        if family not in loaders:
            raise GateFailure(f"no known pristine topology loader for network_id {family!r}")
        if family not in pristine_by_family:
            pristine_by_family[family] = loaders[family]()
        pristine = pristine_by_family[family]
        expected_hash = network_sha256(pristine)
        expected_node_ids = tuple(sorted(pristine.node_name_list))
        expected_candidate_ids = tuple(node for node in expected_node_ids if node in pristine.junction_name_list)
        mismatches = []
        for example in examples[:sample_per_topology]:
            topology = example.topology
            if topology is None:
                mismatches.append({"scenario_id": example.scenario_id, "reason": "missing topology metadata"})
                continue
            if topology.topology_hash != expected_hash:
                mismatches.append(
                    {
                        "scenario_id": example.scenario_id,
                        "reason": "topology_hash does not match recomputed pristine network hash",
                        "recorded": topology.topology_hash,
                        "expected": expected_hash,
                    }
                )
            if topology.node_ids != expected_node_ids:
                mismatches.append(
                    {
                        "scenario_id": example.scenario_id,
                        "reason": "node_ids do not match the pristine topology's node list",
                    }
                )
            if topology.source_candidate_ids != expected_candidate_ids:
                mismatches.append(
                    {
                        "scenario_id": example.scenario_id,
                        "reason": "source_candidate_ids do not match the pristine topology's junction list",
                    }
                )
        checked[family] = {"examples_checked": min(len(examples), sample_per_topology), "mismatches": mismatches}
        if mismatches:
            raise GateFailure(f"topology provenance mismatch for {family!r}: {mismatches}")
    report["checked"] = checked


def gate_normalization_ownership(corpus_dir: Path, report: dict[str, Any], *, normalization_dir: Path) -> None:
    node_path = normalization_dir / "node-normalization.json"
    edge_path = normalization_dir / "edge-normalization.json"
    if not node_path.exists() or not edge_path.exists():
        raise GateFailure(f"normalization artifacts not found under {normalization_dir}")
    saved_node = NormalizationStats.load(node_path)
    saved_edge = NormalizationStats.load(edge_path)

    train_dir = corpus_dir / "tensors" / "train"
    dataset = ShardedScenarioDataset(train_dir, expected_split="train")
    dataset.verify_shard_checksums()
    examples = [dataset[position] for position in range(len(dataset))]
    node_arrays = [example.inputs["node_features"].numpy() for example in examples]
    edge_arrays = [example.inputs["edge_features"].numpy() for example in examples]
    refit_node = NormalizationStats.fit(np.concatenate(node_arrays, axis=0), DEFAULT_FEATURE_SCHEMA.node_features)
    refit_edge = NormalizationStats.fit(np.concatenate(edge_arrays, axis=0), DEFAULT_FEATURE_SCHEMA.edge_features)

    if refit_node.fingerprint != saved_node.fingerprint:
        raise GateFailure(
            "saved node normalization artifact is not reproducible from tensors/train alone "
            f"(refit fingerprint {refit_node.fingerprint} != saved {saved_node.fingerprint}); "
            "it may have been fit on a different or non-train-only dataset"
        )
    if refit_edge.fingerprint != saved_edge.fingerprint:
        raise GateFailure(
            "saved edge normalization artifact is not reproducible from tensors/train alone "
            f"(refit fingerprint {refit_edge.fingerprint} != saved {saved_edge.fingerprint}); "
            "it may have been fit on a different or non-train-only dataset"
        )
    report["node_normalization_sha256"] = saved_node.fingerprint
    report["edge_normalization_sha256"] = saved_edge.fingerprint
    report["train_examples_used_to_refit"] = len(examples)


def gate_label_audit_present(corpus_dir: Path, report: dict[str, Any]) -> None:
    audit = _load_label_audit(corpus_dir)
    if "splits" not in audit or "cross_split_leakage" not in audit:
        raise GateFailure("label-audit.json missing required top-level keys")
    decision_splits = set(audit.get("decision_splits", []))
    forbidden = decision_splits - {"train", "validation", "calibration"}
    if forbidden:
        raise GateFailure(f"decision_splits includes non-governed splits: {sorted(forbidden)}")
    for split, data in audit["splits"].items():
        baselines = data.get("sanity_baselines", {})
        if split not in decision_splits and "note" not in baselines:
            raise GateFailure(f"split {split!r} outside decision_splits has baseline accuracies computed")
    report["decision_splits"] = sorted(decision_splits)
    report["splits_present"] = sorted(audit["splits"])


def gate_mask_round_trip(corpus_dir: Path, report: dict[str, Any]) -> None:
    tensors_root = corpus_dir / "tensors"
    split_dirs = _discover_split_dirs(tensors_root)
    if "train" not in split_dirs:
        raise GateFailure("no train split to sample real examples from")

    dataset = ShardedScenarioDataset(tensors_root / "train", expected_split="train")
    by_family: dict[str, ScenarioExample] = {}
    for position in range(len(dataset)):
        example = dataset[position]
        by_family.setdefault(example.network_id, example)
        if len(by_family) >= 2:
            break
    if len(by_family) < 2:
        raise GateFailure("need at least two distinct topologies in train to exercise variable-topology collation")

    examples = list(by_family.values())
    batch, _targets = collate_variable_topology(examples)
    max_nodes = batch["node_mask"].shape[1]
    max_steps = batch["sensor_mask"].shape[1]
    problems = []
    for index, example in enumerate(examples):
        own_nodes = example.inputs["node_features"].shape[0]
        own_steps = example.inputs["sensor_mask"].shape[0]
        if not bool(batch["node_mask"][index, :own_nodes].all()):
            problems.append({"scenario_id": example.scenario_id, "reason": "own node region not fully True"})
        if own_nodes < max_nodes and bool(batch["node_mask"][index, own_nodes:].any()):
            problems.append({"scenario_id": example.scenario_id, "reason": "padded node region not all False"})
        own_sensor_mask = example.inputs["sensor_mask"]
        if not bool(
            (batch["sensor_mask"][index, :own_steps, :own_nodes] == own_sensor_mask).all()
        ):
            problems.append(
                {"scenario_id": example.scenario_id, "reason": "sensor_mask not preserved exactly in its own region"}
            )
        if own_steps < max_steps and bool(batch["sensor_mask"][index, own_steps:, :].any()):
            problems.append({"scenario_id": example.scenario_id, "reason": "padded time-step region not all False"})
    if problems:
        raise GateFailure(f"mask round-trip failures on real corpus examples: {problems}")

    result = subprocess.run(
        [sys.executable, "-m", "pytest", "-q", "tests/unit/test_variable_collate.py"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise GateFailure(
            f"tests/unit/test_variable_collate.py failed:\n{result.stdout[-4000:]}\n{result.stderr[-2000:]}"
        )
    report["families_checked"] = sorted(by_family)
    report["regression_suite"] = "tests/unit/test_variable_collate.py passed"


def _record_to_manifest(record: dict[str, Any]) -> ScenarioManifest:
    incident_record = dict(record["incident"])
    incident_record["source_nodes"] = tuple(incident_record["source_nodes"])
    return ScenarioManifest(
        scenario_id=UUID(record["scenario_id"]),
        split=DatasetSplit(record["split"]),
        stage=CurriculumStage(record["stage"]),
        network_id=record["network_id"],
        network_family=record["network_family"],
        network_sha256=record["network_sha256"],
        seed=record["seed"],
        seed_family=record["seed_family"],
        simulator_version=record["simulator_version"],
        generator_version=record["generator_version"],
        incident=IncidentTruth(**incident_record),
        sensor_nodes=tuple(record["sensor_nodes"]),
        model_mismatch=record["model_mismatch"],
        artifact_sha256=record["artifact_sha256"],
        replay_sha256=record["replay_sha256"],
        created_with_python=record["created_with_python"],
        event_type=record.get("event_type", "contamination"),
    )


def gate_deterministic_replay(corpus_dir: Path, report: dict[str, Any], *, sample_per_split: int) -> None:
    scenarios_root = corpus_dir / "scenarios"
    loaders = _topology_loaders()
    pristine_cache: dict[str, Any] = {}
    generator = WNTRScenarioGenerator()
    rng = random.Random(20260805)

    checked = []
    mismatches = []
    hash_only_drift = []
    for split in _REPLAY_ELIGIBLE_SPLITS:
        manifest_path = scenarios_root / "manifests" / f"{split.value}.jsonl"
        if not manifest_path.exists():
            continue
        lines = [line for line in manifest_path.read_text(encoding="utf-8").splitlines() if line.strip()]
        sample = rng.sample(lines, k=min(sample_per_split, len(lines)))
        for line in sample:
            record = json.loads(line)
            manifest = _record_to_manifest(record)
            family = manifest.network_family
            if family not in pristine_cache:
                pristine_cache[family] = loaders[family]()
            artifact_path = scenarios_root / split.value / f"{manifest.scenario_id}.npz"
            with np.load(artifact_path) as arrays:
                original = {key: arrays[key] for key in arrays.files}

            config = ScenarioGenerationConfig(
                seed=manifest.seed,
                network_id=manifest.network_id,
                network_family=family,
                split=manifest.split,
                stage=manifest.stage,
                event_type=EventType(manifest.event_type),
                source_node=manifest.incident.source_nodes[0],
                sensor_count=len(manifest.sensor_nodes),
                pipe_outage_probability=0.0,
                **_degradation_probabilities(manifest.stage),
            )
            regenerated = generator.generate(pristine_cache[family], config)
            checked.append(str(manifest.scenario_id))
            if regenerated.manifest.replay_sha256 != manifest.replay_sha256:
                mismatches.append({"scenario_id": str(manifest.scenario_id), "reason": "replay_sha256 differs"})
                continue
            # artifact_sha256 hashes raw float bytes, which is not portable
            # across CPU architectures: IEEE-754 leaves signed-zero results
            # from ops like np.maximum(0.0, x) implementation-defined, so a
            # scenario generated on one architecture and replayed on another
            # can produce a differing hash with bit-identical *values* (-0.0
            # vs. 0.0, which compare equal and are physically the same
            # concentration). Treat a hash-only mismatch as inconclusive and
            # fall through to the semantic array checks below, which are the
            # actual determinism criterion; only fail if those disagree too.
            hash_drifted = regenerated.manifest.artifact_sha256 != manifest.artifact_sha256
            array_mismatch = False
            for key in ("observed_concentration", "observation_mask", "truth_concentration"):
                if not np.array_equal(getattr(regenerated, key), original[key], equal_nan=True):
                    array_mismatch = True
                    mismatches.append(
                        {"scenario_id": str(manifest.scenario_id), "reason": f"{key} array differs on replay"}
                    )
            if hash_drifted and not array_mismatch:
                hash_only_drift.append(str(manifest.scenario_id))
    if not checked:
        raise GateFailure("no train/validation/calibration scenarios available to replay")
    if mismatches:
        raise GateFailure(f"non-deterministic replay: {mismatches}")
    report["scenarios_replayed"] = len(checked)
    report["splits_covered"] = [split.value for split in _REPLAY_ELIGIBLE_SPLITS]
    if hash_only_drift:
        report["artifact_sha256_drift_tolerated"] = hash_only_drift
    report["excluded_split_note"] = (
        "development_holdout excluded: plain curriculum scenarios and the two OOD-holdout "
        "helpers share one manifest file with different degradation-probability formulas "
        "that cannot be distinguished from the manifest alone."
    )


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--corpus-dir", type=Path, required=True)
    parser.add_argument("--normalization-dir", type=Path, default=None, help="default: <corpus-dir>/normalization")
    parser.add_argument("--topology-sample-size", type=int, default=6)
    parser.add_argument("--replay-sample-per-split", type=int, default=4)
    parser.add_argument("--report-output", type=Path, default=None)
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    normalization_dir = args.normalization_dir or (args.corpus_dir / "normalization")

    gates: list[tuple[str, Any]] = [
        ("shard_checksums", lambda r: gate_shard_checksums(args.corpus_dir, r)),
        ("finite_values", lambda r: gate_finite_values(args.corpus_dir, r)),
        ("target_mask_validation", lambda r: gate_target_mask_validation(args.corpus_dir, r)),
        ("leakage", lambda r: gate_leakage(args.corpus_dir, r)),
        (
            "topology_provenance",
            lambda r: gate_topology_provenance(args.corpus_dir, r, sample_per_topology=args.topology_sample_size),
        ),
        (
            "normalization_ownership",
            lambda r: gate_normalization_ownership(args.corpus_dir, r, normalization_dir=normalization_dir),
        ),
        ("label_audit_present", lambda r: gate_label_audit_present(args.corpus_dir, r)),
        ("mask_round_trip", lambda r: gate_mask_round_trip(args.corpus_dir, r)),
        (
            "deterministic_replay",
            lambda r: gate_deterministic_replay(args.corpus_dir, r, sample_per_split=args.replay_sample_per_split),
        ),
    ]

    results: dict[str, Any] = {}
    failures: dict[str, str] = {}
    for name, run in gates:
        detail: dict[str, Any] = {}
        try:
            run(detail)
            results[name] = {"status": "passed", **detail}
        except GateFailure as error:
            results[name] = {"status": "failed", "reason": str(error), **detail}
            failures[name] = str(error)
        except Exception as error:  # noqa: BLE001 -- any unexpected error is a gate failure, not a crash to hide
            results[name] = {"status": "error", "reason": f"{type(error).__name__}: {error}"}
            failures[name] = str(error)

    report = {
        "schema_version": 1,
        "corpus_dir": str(args.corpus_dir),
        "overall_status": "failed" if failures else "passed",
        "gates": results,
    }
    report_output = args.report_output or (args.corpus_dir / "corpus-gates-report.json")
    report_output.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps(report, indent=2, sort_keys=True))

    if failures:
        print(f"\nCORPUS GATES FAILED: {sorted(failures)}", file=sys.stderr)
        return 1
    print("\nall corpus gates passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
