"""core-issues4.txt Section D item 3: candidate_reduction_prediction/
should_continue_sampling_logits Scout heads.

Both targets_v2 targets (candidate_reduction, should_continue_sampling)
already existed and were already generated by
hydroswarm.training.scout_trajectory, but had no model head to receive a
gradient at all -- a governed target with no output can never be trained.
Same net-new-parameters compatibility convention as event_control_heads
(see test_event_control_heads.py), so gated the same way behind
`scout_control_heads` (default False).
"""

from __future__ import annotations

import pytest
import torch

from hydroswarm.model import ArchitectureCompatibilityError, HydroCore, verify_architecture_compatibility
from hydroswarm.training.losses import compute_multitask_loss


def _tiny_model(**overrides) -> HydroCore:
    base = dict(
        node_feature_dim=3,
        temporal_feature_dim=2,
        quality_feature_dim=2,
        d_model=32,
        nhead=4,
        dim_feedforward=64,
        num_layers=1,
        modality_layers=1,
        adapter_dims=(32, 32, 32),
        dropout=0.0,
    )
    base.update(overrides)
    return HydroCore(**base)


def _batch(nodes: int = 4) -> dict:
    generator = torch.Generator().manual_seed(31)
    return {
        "node_features": torch.randn(2, nodes, 3, generator=generator),
        "temporal_features": torch.randn(2, 3, nodes, 2, generator=generator),
        "quality_features": torch.randn(2, 3, nodes, 2, generator=generator),
        "source_candidate_mask": torch.ones(2, nodes, dtype=torch.bool),
    }


def test_default_scout_control_heads_is_disabled() -> None:
    model = _tiny_model()
    assert model.scout_control_heads is False
    assert not hasattr(model, "candidate_reduction_head")
    assert not hasattr(model, "should_continue_sampling_head")


def test_disabled_scout_control_heads_omits_new_output_keys() -> None:
    model = _tiny_model().eval()
    with torch.no_grad():
        output = model(_batch())
    assert "candidate_reduction_prediction" not in output
    assert "should_continue_sampling_logits" not in output


def test_enabling_scout_control_heads_adds_no_other_parameters() -> None:
    disabled_params = set(_tiny_model(scout_control_heads=False).state_dict())
    enabled_params = set(_tiny_model(scout_control_heads=True).state_dict())
    assert disabled_params <= enabled_params
    new_params = enabled_params - disabled_params
    assert all(
        name.startswith(("candidate_reduction_head", "should_continue_sampling_head")) for name in new_params
    )
    assert any(name.startswith("candidate_reduction_head") for name in new_params)
    assert any(name.startswith("should_continue_sampling_head") for name in new_params)


def test_forward_pass_produces_correctly_shaped_outputs_when_enabled() -> None:
    nodes = 4
    model = _tiny_model(scout_control_heads=True).eval()
    with torch.no_grad():
        output = model(_batch(nodes=nodes))
    assert output["candidate_reduction_prediction"].shape == (2, nodes)
    assert output["should_continue_sampling_logits"].shape == (2,)
    assert torch.isfinite(output["candidate_reduction_prediction"]).all()
    assert torch.isfinite(output["should_continue_sampling_logits"]).all()
    # Sigmoid output: candidate_reduction is a fraction in [0, 1]
    # (targets_v2's own documented unit).
    assert (output["candidate_reduction_prediction"] >= 0.0).all()
    assert (output["candidate_reduction_prediction"] <= 1.0).all()


def test_enabling_does_not_change_other_outputs_given_identical_weights() -> None:
    torch.manual_seed(11)
    disabled = _tiny_model(scout_control_heads=False).eval()
    enabled = _tiny_model(scout_control_heads=True).eval()
    shared = set(disabled.state_dict()) & set(enabled.state_dict())
    enabled.load_state_dict(
        {key: value for key, value in disabled.state_dict().items() if key in shared}, strict=False
    )
    batch = _batch()
    with torch.no_grad():
        disabled_output = disabled(batch)
        enabled_output = enabled(batch)
    torch.testing.assert_close(disabled_output["hidden_state"], enabled_output["hidden_state"])
    torch.testing.assert_close(
        disabled_output["expected_information_gain"], enabled_output["expected_information_gain"]
    )


def test_architecture_config_records_scout_control_heads() -> None:
    disabled_config = _tiny_model(scout_control_heads=False).architecture_config()
    enabled_config = _tiny_model(scout_control_heads=True).architecture_config()
    assert disabled_config["scout_control_heads"] is False
    assert enabled_config["scout_control_heads"] is True


def test_verify_architecture_compatibility_rejects_scout_control_heads_mismatch() -> None:
    model = _tiny_model(scout_control_heads=False)
    with pytest.raises(ArchitectureCompatibilityError, match="scout_control_heads"):
        verify_architecture_compatibility(model, {"scout_control_heads": True})


def test_verify_architecture_compatibility_accepts_missing_field_for_old_checkpoints() -> None:
    model = _tiny_model(scout_control_heads=True)
    verify_architecture_compatibility(model, {})  # must not raise


def test_parameter_report_includes_scout_control_heads_only_when_enabled() -> None:
    disabled = _tiny_model(scout_control_heads=False)
    enabled = _tiny_model(scout_control_heads=True)
    disabled_report = disabled.parameter_report()
    enabled_report = enabled.parameter_report()
    assert enabled_report.heads > disabled_report.heads
    assert enabled_report.total == disabled_report.total + (
        enabled.parameter_count() - disabled.parameter_count()
    )


def test_both_heads_receive_a_real_nonzero_gradient_through_compute_multitask_loss() -> None:
    """core-issues4.txt Phase 10 promotion-gate requirement ("the head
    received nonzero gradients") -- proven here at the unit level with a
    real backward pass through the actual loss path, not merely asserted."""

    nodes = 4
    model = _tiny_model(scout_control_heads=True)
    output = model(_batch(nodes=nodes))
    targets = {
        "candidate_reduction": torch.rand(2, nodes),
        "candidate_reduction_mask": torch.ones(2, nodes, dtype=torch.bool),
        "should_continue_sampling": torch.tensor([1.0, 0.0]),
    }
    loss = compute_multitask_loss(output, targets)
    assert set(loss.tasks) == {"candidate_reduction", "should_continue_sampling"}
    loss.total.backward()
    candidate_reduction_grad_norm = sum(
        parameter.grad.norm().item()
        for parameter in model.candidate_reduction_head.parameters()
        if parameter.grad is not None
    )
    should_continue_grad_norm = sum(
        parameter.grad.norm().item()
        for parameter in model.should_continue_sampling_head.parameters()
        if parameter.grad is not None
    )
    assert candidate_reduction_grad_norm > 0.0
    assert should_continue_grad_norm > 0.0


def test_candidate_reduction_respects_node_mask() -> None:
    nodes = 4
    model = _tiny_model(scout_control_heads=True).eval()
    batch = _batch(nodes=nodes)
    batch["node_mask"] = torch.tensor([[True, True, False, False], [True, True, True, False]])
    with torch.no_grad():
        output = model(batch)
    assert torch.equal(
        output["candidate_reduction_prediction"][~batch["node_mask"]],
        torch.zeros_like(output["candidate_reduction_prediction"][~batch["node_mask"]]),
    )
